### ISSUE TITLE
Not compatible with Nullscape

### ISSUE THREAD

**Issue by Todst** [Lyof429/EndsPhantasm#4]
I know this mod is very early into development but I'll like to point out that End's Phantasm's biomes doesn't show up on all Nullscape's biomes including the revamped vanilla ones when using /locate. Though the fallen stars do work as intended.

**Comment by SashaKYotoz** [comment]
What version of mod and Minecraft did you try?

**Comment by Todst** [comment]
1.20.1 and 0.1

from what I'm it seems to be affecting both forge/fabric ports of the mod

**Comment by SashaKYotoz** [comment]
well, will try to fix that in next forge release

**Comment by Lyof429** [comment]
okay i know i'm super late but that's due to nullscape completely overriding the end.
A way to fix this is to edit nullscape's files by making a datapack either to add the dreaming_den as a biome or by changing phantasm's is_dreaming_den biome tag to include the vanilla end highlands (so it gets all the biome's features)
